name: codable_plus
description: A serialization library for converting dynamic, structured data (JSON, YAML) into Dart types. Forked for null safety and some minor fixes.
version: 1.0.1
homepage: https://github.com/t-unit/dart-codable-plus

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  meta: ">=1.15.0 <2.0.0"

dev_dependencies:
  test: ">=1.25.7 <2.0.0"
